### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by beztpro9** [Fadi002/de4py#16]
Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

D:\de4py-main\de4py-main>python main
python: can't open file 'D:\\de4py-main\\de4py-main\\main': [Errno 2] No such file or directory

D:\de4py-main\de4py-main>python main.py
Traceback (most recent call last):
  File "D:\de4py-main\de4py-main\main.py", line 12, in <module>
    import os, msvcrt, eel, logging, requests, platform, threading, psutil, colorama, signal, zlib
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\eel\__init__.py", line 16, in <module>
    import bottle.ext.websocket as wbs
ModuleNotFoundError: No module named 'bottle.ext.websocket'

D:\de4py-main\de4py-main>

Is there any way to fix this, Im pretty new at python and other programming languages or basic computer knowledge.

**Comment by beztpro9** [comment]
Just found the asnwer on discord, Thanks!!
